import type { OAuthCredentials, OAuthLoginCallbacks, OAuthProviderInterface } from "./types.ts";

const COMMANDCODE_AUTH_URL = "https://commandcode.ai/studio/auth/cli";
const TEN_YEARS_MS = 10 * 365 * 24 * 60 * 60 * 1000;

function sanitizeApiKey(input: string): string {
	const esc = String.fromCharCode(27);
	return Array.from(
		input.replaceAll(`${esc}[200~`, "").replaceAll(`${esc}[201~`, "").replaceAll("[200~", "").replaceAll("[201~", ""),
	)
		.filter((char) => {
			const code = char.charCodeAt(0);
			return code > 31 && code !== 127;
		})
		.join("")
		.trim();
}

function credentialsFromApiKey(apiKey: string): OAuthCredentials {
	return {
		refresh: apiKey,
		access: apiKey,
		expires: Date.now() + TEN_YEARS_MS,
	};
}

export async function loginCommandCode(callbacks: OAuthLoginCallbacks): Promise<OAuthCredentials> {
	callbacks.onAuth({
		url: COMMANDCODE_AUTH_URL,
		instructions:
			"Sign in with your Command Code subscription. If automatic transfer is unavailable, paste the generated key here.",
	});

	const apiKey = sanitizeApiKey(
		await callbacks.onPrompt({
			message: "Paste the Command Code key generated by the browser subscription login:",
		}),
	);
	if (!apiKey) throw new Error("No Command Code key provided");
	return credentialsFromApiKey(apiKey);
}

export async function refreshCommandCodeToken(credentials: OAuthCredentials): Promise<OAuthCredentials> {
	return credentialsFromApiKey(credentials.refresh);
}

export const commandCodeOAuthProvider: OAuthProviderInterface = {
	id: "commandcode",
	name: "Command Code",
	login: loginCommandCode,
	refreshToken: refreshCommandCodeToken,
	getApiKey: (credentials) => credentials.access,
};
